import streamlit as st
import random
from analyze import analyze_input
from generate_code import Generator_code_C
import time
st.set_page_config(
    "Algorithm To C - ElenaAlgorithm",
    ":computer:",
    "wide"
)

if "messages" not in st.session_state:
    st.session_state["messages"] = []

if 'key' not in st.session_state:
    st.session_state['key'] = f'user_{random.randint(1000000, 999999999)}'

if 'showed' not in st.session_state:
    st.session_state['showed'] = 1
st.markdown("<style>.stApp {background:#0e1117 }</style>",unsafe_allow_html = 1)
if st.session_state['showed'] == 1:
    st.toast(f"Bienvenue {st.session_state['key']}", icon="👋")
    st.session_state['showed'] += 1

result = []

chat_input = st.chat_input("Algorithms")


if chat_input is not None or len(st.session_state['messages']) >0:
    message_data = {
        "user": st.session_state['key'],
        "message": chat_input,
        "result": chat_input
    }
    st.session_state["messages"].append(message_data)
    
if st.session_state['messages']:
    if st.button("Clear All Messages"):
        st.session_state["messages"].clear()
    with st.chat_message("user"):
        for i in range(0, len(st.session_state["messages"])):
            with st.container(border=1):
                st.code(st.session_state["messages"][i])
else: 
    with st.chat_message("ai"):
        st.write("Elena") 
        st.write("""Elena est une entreprise qui se consacre à améliorer l'expérience d'apprentissage et à faciliter la vie académique des étudiants. En proposant des outils, des ressources et des plateformes innovants, Elena vise à rationaliser les processus d'étude et à améliorer l'efficacité globale de l'éducation. L'entreprise s'engage à créer des solutions qui rendent l'apprentissage plus accessible mais aussi plus agréable, aidant les étudiants à atteindre leurs objectifs académiques avec moins de stress. Que ce soit par le biais d'aides à l'étude personnalisées, d'environnements d'apprentissage interactifs ou d'outils efficaces de gestion du temps, Elena s'efforce de responsabiliser les étudiants et de rendre leur parcours éducatif plus fluide et plus productif.""")


# res = ""
# with st.container(border = 1):
#     col_input,col_output = st.columns(2)
#     r = ''
#     with col_input:
#         VariableInput = st.text_area("Variables","Variables\n",height=225)
#         codeInput = st.text_area("Algorithm",height=550)
#         if st.sidebar.button("Run"):
#             res,r = analyze_input(codeInput)
#     with col_output:
#         st.write("Code C")
#         code_output = """
#         //Powered by Elena | Copyright © 2024\n
# //Generated by Elena\n\n#include<stdio.h>\n#include<string.h>\n#include<math.h>\n#include<ctype.h>\n"""
#         for i in range(len(res)):
#             st.code(res[i])
#             def output():
#                 for c in r[i].split(" "):
#                     yield c + " "
#                     time.sleep(.02)
        
#             st.write_stream(output)
#         result.append(res)
    
# if result:
#     st.sidebar.table((result))